version: "3.9"

networks:
  redis-network:

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    networks:
      - redis-network
    depends_on:
      - redis
